from __future__ import annotations

from heya.web.config.constants import (
    TIMEOUT_MIN,
    TIMEOUT_MAX,
    TIMEOUT_DEFAULT,
    TIMEOUT_STEP,
    QUALITY_HIGH,
    QUALITY_MEDIUM,
    QUALITY_LOW,
    MAX_FILES_PER_BATCH,
    MERGE_TITLE_MARKDOWN,
    MERGE_TITLE_WECHAT,
    FILENAME_PREFIX_MARKDOWN,
    FILENAME_PREFIX_WECHAT,
)

__all__ = [
    "TIMEOUT_MIN",
    "TIMEOUT_MAX",
    "TIMEOUT_DEFAULT",
    "TIMEOUT_STEP",
    "QUALITY_HIGH",
    "QUALITY_MEDIUM",
    "QUALITY_LOW",
    "MAX_FILES_PER_BATCH",
    "MERGE_TITLE_MARKDOWN",
    "MERGE_TITLE_WECHAT",
    "FILENAME_PREFIX_MARKDOWN",
    "FILENAME_PREFIX_WECHAT",
]
