from __future__ import annotations

__all__ = [
    "TIMEOUT_MIN",
    "TIMEOUT_MAX",
    "TIMEOUT_DEFAULT",
    "TIMEOUT_STEP",
    "QUALITY_HIGH",
    "QUALITY_MEDIUM",
    "QUALITY_LOW",
    "MAX_FILES_PER_BATCH",
    "MERGE_TITLE_MARKDOWN",
    "MERGE_TITLE_WECHAT",
    "FILENAME_PREFIX_MARKDOWN",
    "FILENAME_PREFIX_WECHAT",
]

TIMEOUT_MIN = 5
TIMEOUT_MAX = 300
TIMEOUT_DEFAULT = 60
TIMEOUT_STEP = 5

QUALITY_HIGH = 0
QUALITY_MEDIUM = 1
QUALITY_LOW = 2

MAX_FILES_PER_BATCH = 50

MERGE_TITLE_MARKDOWN = "Markdown 文档合集"
MERGE_TITLE_WECHAT = "微信公众号文章合集"
FILENAME_PREFIX_MARKDOWN = "merged_markdown"
FILENAME_PREFIX_WECHAT = "merged_wechat"
